name: 'Publish Docker image'
description: 'Publish Docker images to a registry (GitHub Packages)'
inputs:
  registry:
    description: "The registry where to publish"
    required: true
    default: ghcr.io
  image-name:
    description: "The name of the image"
    required: true
    default: ${{ github.repository }}
  github-token:
    description: "The token to log in to the container registry"
    required: true
    default: "devCqen"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Log in to the Container registry
      #uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      #uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      uses: docker/metadata-action@v5
      with:
        images: ${{inputs.registry}}/${{inputs.image-name}}

    - name: Build and push Docker image
      id: push
      #uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }} 

    - name: Generate artifact attestation
      # only if public repository
      if: github.repository_visibility == 'public' #not allowed for private repositories
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{inputs.registry}}/${{inputs.image-name}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true                     
